spring:
  application:
    name: users
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:users
    username: sa
  jpa:
    defer-datasource-initialization: true
catalog:
  url: https://catalog-workshop-yequy5sv5a-uc.a.run.app/catalog
