server:
  servlet:
    context-path: /
  port: ${PORT:8080}

spring:
  application:
    name: users

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.175.164.238:3306/UsersDB
    username: user
    password: user

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

catalog:
  url: https://catalog-workshop-yequy5sv5a-uc.a.run.app/catalog
