server:
  servlet:
    context-path: /
  port: ${PORT:8081}

spring:
  application:
    name: users

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://google/Users?cloudSqlInstance=microservice-424612:europe-southwest1:usermicroservice&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    url: jdbc:mysql://db:3306/mydb
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

catalog:
  url: https://catalog-workshop-yequy5sv5a-uc.a.run.app/catalog
