server:
  servlet:
    context-path: /catalog
  port: ${PORT:8080}

spring:
  application:
    name: users
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:users
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    defer-datasource-initialization: true
catalog:
  url: https://catalog-workshop-yequy5sv5a-uc.a.run.app/catalog
